### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by jgautheron** [matttproud/gochecklist#7]
How about recommending the use of a `Makefile` for abstracting the most basic commands?
Such as `make build`, `make test`, `make check`, `make image`...

**Comment by jbuberel** [comment]
Tempting, but it would be tough to convince the Go community that this is a generally accepted standard practice. 

It also complicates cross-platform distribution and may result in projects not being go get-able.

Is that a reasonable assessment?

**Comment by jgautheron** [comment]
Good points. Maybe we could see this point as a recommendation under the Good Citizen section?
Most companies will want a `Makefile` for streamlining their application workflow.

I'd love to see something similar to [h5bp/server-configs-nginx](https://github.com/h5bp/server-configs-nginx), a boilerplate for Go projects. But now I'm straying from the original scope of this project. We could take that somewhere else if you're interested in the idea.

**Comment by jbuberel** [comment]
For applications, perhaps. But for libraries in the Go ecosystem, probably not. 

But I do like the idea of a collection of example Go projects (a web app, a CLI, etc.).  Probably best that we take that conversation to a new venue. Feel free to contact me - jbuberel@google.com.
