### ISSUE TITLE
Automated checks

### ISSUE THREAD

**Issue by jgautheron** [matttproud/gochecklist#8]
How about [recommending the use of tools](https://medium.com/@jgautheron/quality-pipeline-for-go-projects-497e34d6567) which are statically checking the source code for common errors, potential pitfalls and suggestions for improvements?

A few examples:
- go vet — Reports potential errors that otherwise compile.
- go vet — shadow — Reports variables that may have been unintentionally shadowed.
- gotype — Syntactic and semantic analysis similar to the Go compiler.
- deadcode — Finds unused code.
- gocyclo — Computes the cyclomatic complexity of functions.
- golint — Google’s (mostly stylistic) linter.
- defercheck — Checks for duplicate defer calls.
- varcheck — Find unused global variables and constants.
- structcheck — Find unused struct fields.
- errcheck — Check that error return values are used.
- dupl — Reports potentially duplicated code.

**Comment by matrixik** [comment]
Or even better link straight to [gometalinter](https://github.com/alecthomas/gometalinter)

**Comment by jbuberel** [comment]
@jgautheron @matrixik - Great suggestions. Adding the gometalinter instructions now.

**Comment by jbuberel** [comment]
https://github.com/matttproud/gochecklist/blob/master/publication/code_correctness.md

**Comment by jgautheron** [comment]
:+1:
